'use strict';

// Companies whose public job boards (no API key needed) list jobs in India.
// Each entry was checked against the live board before being added.
// provider: greenhouse | lever | smartrecruiters | ashby
// slug:     the company's board id on that provider
module.exports = [
  { provider: 'lever', slug: 'paytm', name: 'Paytm' },
  { provider: 'greenhouse', slug: 'okta', name: 'Okta' },
  { provider: 'greenhouse', slug: 'databricks', name: 'Databricks' },
  { provider: 'greenhouse', slug: 'purestorage', name: 'Pure Storage' },
  { provider: 'greenhouse', slug: 'mongodb', name: 'MongoDB' },
  { provider: 'smartrecruiters', slug: 'ServiceNow', name: 'ServiceNow' },
  { provider: 'greenhouse', slug: 'zscaler', name: 'Zscaler' },
  { provider: 'smartrecruiters', slug: 'NielsenIQ', name: 'NielsenIQ' },
  { provider: 'ashby', slug: 'sarvam', name: 'Sarvam AI' },
  { provider: 'lever', slug: 'meesho', name: 'Meesho' },
  { provider: 'greenhouse', slug: 'stripe', name: 'Stripe' },
  { provider: 'greenhouse', slug: 'celonis', name: 'Celonis' },
  { provider: 'smartrecruiters', slug: 'Experian', name: 'Experian' },
  { provider: 'greenhouse', slug: 'rubrik', name: 'Rubrik' },
  { provider: 'smartrecruiters', slug: 'Freshworks', name: 'Freshworks' },
  { provider: 'greenhouse', slug: 'gitlab', name: 'GitLab' },
  { provider: 'greenhouse', slug: 'netskope', name: 'Netskope' },
  { provider: 'lever', slug: 'zeta', name: 'Zeta' },
  { provider: 'greenhouse', slug: 'fivetran', name: 'Fivetran' },
  { provider: 'greenhouse', slug: 'toast', name: 'Toast' },
  { provider: 'lever', slug: 'fampay', name: 'FamPay' },
  { provider: 'greenhouse', slug: 'hackerrank', name: 'HackerRank' },
  { provider: 'lever', slug: 'mindtickle', name: 'Mindtickle' },
  { provider: 'greenhouse', slug: 'elastic', name: 'Elastic' },
  { provider: 'greenhouse', slug: 'twilio', name: 'Twilio' },
  { provider: 'greenhouse', slug: 'sentinellabs', name: 'SentinelOne' },
  { provider: 'greenhouse', slug: 'druva', name: 'Druva' },
  { provider: 'greenhouse', slug: 'coinbase', name: 'Coinbase' },
  { provider: 'greenhouse', slug: 'newrelic', name: 'New Relic' },
  { provider: 'greenhouse', slug: 'datadog', name: 'Datadog' },
  { provider: 'lever', slug: 'cred', name: 'CRED' },
  { provider: 'greenhouse', slug: 'groww', name: 'Groww' },
  { provider: 'greenhouse', slug: 'samsara', name: 'Samsara' },
  { provider: 'greenhouse', slug: 'airbnb', name: 'Airbnb' },
  { provider: 'greenhouse', slug: 'sumologic', name: 'Sumo Logic' },
  { provider: 'greenhouse', slug: 'anthropic', name: 'Anthropic' },
  { provider: 'ashby', slug: 'atlan', name: 'Atlan' },
  { provider: 'greenhouse', slug: 'mixpanel', name: 'Mixpanel' },
  { provider: 'smartrecruiters', slug: 'Ubisoft2', name: 'Ubisoft' },
  { provider: 'ashby', slug: 'notion', name: 'Notion' },
  { provider: 'greenhouse', slug: 'figma', name: 'Figma' },
  { provider: 'greenhouse', slug: 'cloudflare', name: 'Cloudflare' },
  { provider: 'greenhouse', slug: 'scaleai', name: 'Scale AI' },
  { provider: 'smartrecruiters', slug: 'BoschGroup', name: 'Bosch' },
  { provider: 'smartrecruiters', slug: 'Swiggy', name: 'Swiggy' },
  { provider: 'smartrecruiters', slug: 'Wabtec', name: 'Wabtec' },
  { provider: 'smartrecruiters', slug: 'Sutherland', name: 'Sutherland' },
  { provider: 'lever', slug: 'hevodata', name: 'Hevo Data' },
  { provider: 'smartrecruiters', slug: 'Continental', name: 'Continental' },
  { provider: 'greenhouse', slug: 'kaseya', name: 'Kaseya' },
  { provider: 'greenhouse', slug: 'onetrust', name: 'OneTrust' },
  { provider: 'greenhouse', slug: 'razorpaysoftwareprivatelimited', name: 'Razorpay' },
  { provider: 'greenhouse', slug: 'zoominfo', name: 'ZoomInfo' },
  { provider: 'greenhouse', slug: 'tripactions', name: 'Navan' },
  { provider: 'greenhouse', slug: 'truecaller', name: 'Truecaller' },
  { provider: 'greenhouse', slug: 'roblox', name: 'Roblox' },
  { provider: 'greenhouse', slug: 'launchdarkly', name: 'LaunchDarkly' },
  { provider: 'greenhouse', slug: 'yugabyte', name: 'YugabyteDB' },
  { provider: 'greenhouse', slug: 'zuora', name: 'Zuora' },
  { provider: 'greenhouse', slug: 'workato', name: 'Workato' },
  { provider: 'greenhouse', slug: 'coursera', name: 'Coursera' },
  { provider: 'greenhouse', slug: 'jfrog', name: 'JFrog' },
  { provider: 'greenhouse', slug: 'turing', name: 'Turing' },
  { provider: 'greenhouse', slug: 'deliveroo', name: 'Deliveroo' },
  { provider: 'greenhouse', slug: 'thoughtworks', name: 'Thoughtworks' },
  { provider: 'smartrecruiters', slug: 'Unacademy', name: 'Unacademy' },
  { provider: 'greenhouse', slug: 'grafanalabs', name: 'Grafana Labs' },
  { provider: 'greenhouse', slug: 'simpplr', name: 'Simpplr' },
  { provider: 'greenhouse', slug: 'salesloft', name: 'Salesloft' },
  { provider: 'greenhouse', slug: 'vercel', name: 'Vercel' },
  { provider: 'lever', slug: 'pocketfm', name: 'Pocket FM' },
  { provider: 'greenhouse', slug: 'cockroachlabs', name: 'Cockroach Labs' },
  { provider: 'greenhouse', slug: 'hubspotjobs', name: 'HubSpot' },
  { provider: 'smartrecruiters', slug: 'Endava', name: 'Endava' },
  { provider: 'ashby', slug: 'smallest', name: 'Smallest AI' },

  // Remote-job board (not a single company): remote jobs open to India.
  { provider: 'jobicy', slug: 'anywhere', name: 'Jobicy', source: 'Jobicy' },
  { provider: 'jobicy', slug: 'apac', name: 'Jobicy', source: 'Jobicy' },
];
